version: '3.8'
services:
  api:
    image: iamdudumon/my-nest-app
    container_name: test-api
    ports:
      - "80:3000"
    mem_limit: ${MEM:-128m}
    cpus: ${CPU:-0.25}
    networks:
      - monitor_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/kmsg:/dev/kmsg
    networks:
      - monitor_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor_net

  k6:
    image: grafana/k6
    container_name: k6
    ports:
      - "6565:6565"
    depends_on:
      - api
    volumes:
      - ../:/src
    entrypoint: ["sh", "-c"]
    command: >
      "until wget -qO- http://test-api:3000/boards; do echo 'waiting for api...'; sleep 1; done; k6 run --out prometheus-remote-write=http://prometheus:9090/api/v1/write /src/k6_script.test.ts"
    networks:
      - monitor_net

networks:
  monitor_net:
    driver: bridge
